Add Data Factory scanner
Azure/azqr pull request #133
Opened 2023-07-24 15:55 UTC by nachoalonsoportillo

# Description

Adding Azure Data Factory support.

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #103

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [x] Code compiles correctly
* [x] Created/updated tests
* [x] Unit tests passing

2023-07-25 06:00 UTC, cmendible requested changes
@nachoalonsoportillo thanks for this one! We need to add a couple of rules more and corresponding tests and we'll be ready to merge

2023-07-25 06:00 UTC, cmendible commented on internal/scanners/adf/rules.go
> +		},
please add a rule to check for private endpoints.

2023-07-25 06:00 UTC, cmendible commented on internal/scanners/adf/rules.go
> +		},
According to: https://learn.microsoft.com/en-us/azure/reliability/availability-zones-service-support Data Factory supports Availabilty zones. Let's add the rule.

2023-07-25 09:20 UTC, nachoalonsoportillo commented on internal/scanners/adf/rules.go
> +		},
Completed. Done using the same approach you used in the AppServiceScanner (ie searching in the PrivateEndpoints map fetched from the ScanContext passed to the rule's function.)

2023-07-25 18:02 UTC, nachoalonsoportillo commented on internal/scanners/adf/rules.go
> +		},
Waiting for confirmation from Mario Zimmermann but, apparently, zonal protection is always there for the different components behind an instance of an ADF workspace. This is definitely not something that end users can configure.

2023-07-26 12:02 UTC, nachoalonsoportillo commented on internal/scanners/adf/rules.go
> +		},
It seems AZs is not there yet and is not expected to be before end of August. I wouldn't wait to merge this scanner until then or even later, when the GO SDK catches up with those changes should they show up on the REST API surface.

2023-07-26 14:52 UTC, cmendible commented on internal/scanners/adf/rules.go
> +		},
Agree

2023-07-26 14:53 UTC, cmendible approved these changes
LGTM

2023-07-26 19:28 UTC, closed without merging