feature: add Azure VPN Gateway scanner
Azure/azqr pull request #207
Opened 2024-04-23 15:24 UTC by vanwinkelseppe

# Description

Add a scanner for Azure VPN Gateway

## Issue reference

We strive to have all PR being opened based on an issue, where the problem or feature have been discussed prior to implementation.

Please reference the issue this PR will close: #_[206]_

## Checklist

Please make sure you've completed the relevant tasks for this PR, out of the following list:

* [ ] Code compiles correctly
* [ ] Created/updated tests
* [ ] Unit tests passing

2024-04-23 15:25 UTC, vanwinkelseppe commented
@cmendible 
I'm not 100% familiar with the Go SDK for Azure, but do you have an idea where we find the Azure VPN Gateway SKU & Generation in the properties? I wasn't able to locate them.

You have any requests for other scan rules?

Thanks!

2024-04-23 15:38 UTC, cmendible commented on internal/scanners/vpng/rules.go
> +				//TODO: Filter SKU based on tier (BASIC / Or others)
Let's do this before merging

2024-04-23 16:55 UTC, cmendible commented
@vanwinkelseppe I'm about to merge: https://github.com/Azure/azqr/pull/214 so please check if the new SDK for networking helps you with the SLA rule we are reviewing

2024-04-23 16:56 UTC, vanwinkelseppe commented
@cmendible will do thanks!

2024-04-23 20:38 UTC, vanwinkelseppe commented
@cmendible Still no SKU on the VPNGateway, bypassed it by querying for the VirtualNetworkGateway.

Ready for review, have to do the list of rules, but with all the merges I'll do it when it looks ready to go!

2024-04-25 10:59 UTC, cmendible requested changes

2024-04-25 10:59 UTC, cmendible commented on internal/scanners/vpng/rules.go
> +	for k, v := range a.GetVirtualNetworkGatewayRules() {
The intention here was to call the other set of rules right?

@vanwinkelseppe check this one please.

2024-04-25 10:59 UTC, cmendible commented on docs/content/en/docs/Recommendations/_index.md
please rebase. There is no need to manually update this file. It's generated with each build

2024-04-25 16:27 UTC, cmendible requested changes
Hey! Check the following branch: https://github.com/Azure/azqr/tree/vpn I made some changes so we only query for Virtual Network Gateway objects  and take decisions based on the type.

If you are ok with it  merge it into your PR and if possible add an Availability Zone rule based on the service tier.

2024-04-25 16:30 UTC, vanwinkelseppe commented
> Hey! Check the following branch: https://github.com/Azure/azqr/tree/vpn I made some changes so we only query for Virtual Network Gateway objects and take decisions based on the type.
> 
> If you are ok with it merge it into your PR and if possible add an Availability Zone rule based on the service tier.

Will do tonight or tomorrow! Thanks for the refactor!

2024-04-25 19:39 UTC, vanwinkelseppe commented
@cmendible, uncertain for the availability zones.
I've checked the properties on virtualnetworkgateway, but couldn't find anything related to it except ExtendedLocation. But uncertain what this actually means. I've queried some resources on my environment via api to see, but it seems to be never filled in.

I did make a list of which gateway skus can enable them:
[Express](https://learn.microsoft.com/en-us/azure/expressroute/expressroute-about-virtual-network-gateways):
- ErGw1AZ
- ErGw2AZ
- ErGw3AZ

[VPN](url)
- Gen 1 - VpnGw1AZ
- Gen 1 - VpnGw2AZ
- Gen 1 - VpnGw3AZ
- Gen 2 - VpnGw2AZ
- Gen 2 - VpnGw3AZ
- Gen 2 - VpnGw4AZ
- Gen 2 - VpnGw5AZ

2024-04-26 07:47 UTC, cmendible requested changes

2024-04-26 07:47 UTC, cmendible commented on docs/content/en/docs/Overview/_index.md
> +* Azure VPN Gateway
Let's add the other 2 types: local and express route

2024-05-03 00:31 UTC, cmendible approved these changes
LGTM

2024-05-03 00:36 UTC, cmendible requested changes

2024-05-03 00:36 UTC, cmendible commented on internal/scan.go
> +	"github.com/Azure/azqr/internal/scanners/vgw"
Can we move this line to the bottom as the rest of imports?

2024-05-08 12:33 UTC, cmendible submitted a review, later dismissed

2024-05-14 08:55 UTC, cmendible commented
> @cmendible, uncertain for the availability zones. I've checked the properties on virtualnetworkgateway, but couldn't find anything related to it except ExtendedLocation. But uncertain what this actually means. I've queried some resources on my environment via api to see, but it seems to be never filled in.
> 
> I did make a list of which gateway skus can enable them: [Express](https://learn.microsoft.com/en-us/azure/expressroute/expressroute-about-virtual-network-gateways):
> 
> * ErGw1AZ
> * ErGw2AZ
> * ErGw3AZ
> 
> [VPN](url)
> 
> * Gen 1 - VpnGw1AZ
> * Gen 1 - VpnGw2AZ
> * Gen 1 - VpnGw3AZ
> * Gen 2 - VpnGw2AZ
> * Gen 2 - VpnGw3AZ
> * Gen 2 - VpnGw4AZ
> * Gen 2 - VpnGw5AZ

@vanwinkelseppe let's use the SKU, and if SKU (to lower) contains `az` then the Gateway is compliant.

2024-05-16 11:11 UTC, cmendible commented
Closed in favor of: https://github.com/Azure/azqr/pull/237

2024-05-16 11:11 UTC, closed without merging